[0.862s] Invoking command in '/home/isa/ros2_ws/src/examples/launch_testing/launch_testing_examples': AMENT_PREFIX_PATH=/home/isa/ros2_ws/install/launch_testing_examples:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/isa/ros2_ws/build/launch_testing_examples/pytest.xml --junit-prefix=launch_testing_examples -o cache_dir=/home/isa/ros2_ws/build/launch_testing_examples/.pytest_cache PYTHONPATH=/home/isa/ros2_ws/build/launch_testing_examples:/home/isa/ros2_ws/install/launch_testing_examples/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
[1.148s] [1m============================= test session starts ==============================[0m
[1.148s] platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[1.155s] cachedir: /home/isa/ros2_ws/build/launch_testing_examples/.pytest_cache
[1.155s] rootdir: /home/isa/ros2_ws/src/examples/launch_testing/launch_testing_examples
[1.155s] plugins: ament-lint-0.14.1, launch-testing-ros-0.24.0, ament-pep257-0.14.1, ament-copyright-0.14.1, ament-flake8-0.14.1, ament-xmllint-0.14.1, launch-testing-2.0.1, cov-3.0.0, colcon-core-0.12.1
[1.437s] [1mcollecting ... [0m[1m
[1.437s] collected 9 items                                                              [0m
[1.437s] 
[2.609s] launch_testing_examples/check_msgs_launch_test.py [32m.[0m[33m                      [ 11%][0m
[24.427s] launch_testing_examples/check_multiple_nodes_launch_test.py [32m.[0m[33m            [ 22%][0m
[29.773s] launch_testing_examples/check_node_launch_test.py [32m.[0m[33m                      [ 33%][0m
[29.778s] launch_testing_examples/hello_world_launch_test.py [32m.[0m[33m                     [ 44%][0m
[32.969s] launch_testing_examples/record_rosbag_launch_test.py [32m.[0m[33m                   [ 55%][0m
[33.345s] launch_testing_examples/set_param_launch_test.py [32m.[0m[33m                       [ 66%][0m
[33.553s] test/test_copyright.py [32m.[0m[33m                                                 [ 77%][0m
[33.645s] test/test_flake8.py [32m.[0m[33m                                                    [ 88%][0m
[33.675s] test/test_pep257.py [32m.[0m[33m                                                    [100%][0m
[33.675s] 
[33.675s] [33m=============================== warnings summary ===============================[0m
[33.675s] launch_testing_examples/check_msgs_launch_test.py: 2 warnings
[33.675s] launch_testing_examples/check_multiple_nodes_launch_test.py: 2 warnings
[33.675s] launch_testing_examples/check_node_launch_test.py: 2 warnings
[33.675s] launch_testing_examples/hello_world_launch_test.py: 2 warnings
[33.675s] launch_testing_examples/record_rosbag_launch_test.py: 2 warnings
[33.676s] launch_testing_examples/set_param_launch_test.py: 2 warnings
[33.676s]   Warning: There is no current event loop
[33.676s] 
[33.676s] launch_testing_examples/check_msgs_launch_test.py::launch_testing_examples.check_msgs_launch_test
[33.676s]   Warning: Exception in thread Thread-1 (spin)
[33.676s]   
[33.676s]   Traceback (most recent call last):
[33.676s]     File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[33.676s]       self.run()
[33.676s]     File "/usr/lib/python3.10/threading.py", line 953, in run
[33.676s]       self._target(*self._args, **self._kwargs)
[33.676s]     File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 280, in spin
[33.677s]       self.spin_once()
[33.677s]     File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 717, in spin_once
[33.677s]       handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[33.677s]     File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 703, in wait_for_ready_callbacks
[33.677s]       return next(self._cb_iter)
[33.677s]     File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 604, in _wait_for_ready_callbacks
[33.677s]       raise ExternalShutdownException()
[33.677s]   rclpy.executors.ExternalShutdownException
[33.677s] 
[33.677s] test/test_flake8.py::test_flake8
[33.677s] test/test_flake8.py::test_flake8
[33.677s]   Warning: SelectableGroups dict interface is deprecated. Use select.
[33.678s] 
[33.678s] -- Docs: https://docs.pytest.org/en/stable/warnings.html
[33.678s] - generated xml file: /home/isa/ros2_ws/build/launch_testing_examples/pytest.xml -
[33.678s] [33m======================= [32m9 passed[0m, [33m[1m15 warnings[0m[33m in 32.53s[0m[33m ========================[0m
[33.860s] Invoked command in '/home/isa/ros2_ws/src/examples/launch_testing/launch_testing_examples' returned '0': AMENT_PREFIX_PATH=/home/isa/ros2_ws/install/launch_testing_examples:${AMENT_PREFIX_PATH} PYTEST_ADDOPTS=--tb=short --junit-xml=/home/isa/ros2_ws/build/launch_testing_examples/pytest.xml --junit-prefix=launch_testing_examples -o cache_dir=/home/isa/ros2_ws/build/launch_testing_examples/.pytest_cache PYTHONPATH=/home/isa/ros2_ws/build/launch_testing_examples:/home/isa/ros2_ws/install/launch_testing_examples/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 -m pytest
